### ISSUE TITLE
css3 的@supports 的介绍

### ISSUE THREAD

**Issue by madfour** [madfour/blog#10]
`@supports`CSS3新规则之一。主要用于检测当前浏览器是否支持某个CSS属性并加载具体样式;
主要用在防止旧浏览器不支持某些属性造成排版混乱的情况，使用@supports当做备选项。
支持的逻辑运算符：（与 and， 或 or ，非 not）。可使用圆括号控制优先级
基本用法示例：
```CSS
@supports (display: grid) {
    .container {
        color: red;
    }
}
/* 当浏览器支持display:grid这个CSS属性时才应用其中的样式 */
```
其它示例：
```css
/* and 判断  浏览器支持  ‘-webkit-mask: none’  and（与&&）不支持（not）‘caret-color: #fff */
@supports (-webkit-mask: none) and (not (caret-color: #fff)) { ... }

/* and 判断  浏览器不支持‘-webkit-mask: none’  or（或||）支持‘caret-color:  $cursor’ */
@supports (not(-webkit-mask: none)) or (caret-color: $cursor) {...}

/* and 判断  浏览器支持  ‘-webkit-mask: none’  not（非！）不支持（not）‘caret-color:  #fff’ */
@supports (-webkit-mask: none) and (not(caret-color: #fff)) {...}

```
