### ISSUE TITLE
如何让一个div水平垂直居中?

### ISSUE THREAD

**Issue by madfour** [madfour/blog#13]
```html
<div class="parent">
  <div class="child">1</div>
</div>
```

### 第一种`flex`
```css
div.parent {
    display: flex;
    justify-content: center;
    align-items: center;
}
```

### 第二种`grid`
```css
div.parent {
    display: grid;
}
div.child {
    justify-self: center;
    align-self: center;
}
```

### 第三种`vertical-align: middle`
```css
div.parent {
    font-size: 0;
    text-align: center;
    &::before {
        content: "";
        display: inline-block;
        width: 0;
        height: 100%;
        vertical-align: middle;
    }
}
div.child{
  display: inline-block;
  vertical-align: middle;
}
```

### 第四种: 使用`position`+`transform`或`margin`；（缺点是：要有确定宽高）
```css
div.parent {
    position: relative; 
}
div.child {
    position: absolute; 
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);  
}
/* 或者 */
div.child {
    width: 50px;
    height: 10px;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-left: -25px;
    margin-top: -5px;
}
/* 或 */
div.child {
    width: 50px;
    height: 10px;
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    margin: auto;
}
```
