### ISSUE TITLE
如何清除浮动?

### ISSUE THREAD

**Issue by madfour** [madfour/blog#15]
清除浮动不是不用浮动，而是清除 ‘ 浮动产生的父容器高度塌陷 ’ 。

### 方式一 `clear:both`
在最后一个子元素新添加最后一个冗余元素，然后将其设置clear:both,这样就可以清除浮动。
注意：即在父级元素末尾添加的元素必须是一个块级元素，否则无法撑起父级元素高度。
```html
<div id="wrap">
  <div id="inner"></div>
  <div style="clear: both;"></div>
</div>
```
缺点：需要添加大量没有意义的冗余元素

### 方式二：伪元素清除浮动（推荐使用）
`clear:both`结合 :after 伪元素和 IEhack ，可以完美兼容当前主流的各大浏览器，这里的 IEhack 指的是触发 hasLayout。
```html
<div  class="clearfix">
    <div id="inner"></div>
</div>
```

```css
/*开启haslayout*/
.clearfix {
    *zoom: 1;
}
/*ie6 7 不支持伪元素*/
.clearfix:after {
    content: '';
    display: block;
    clear: both;
    height:0;
    line-height:0;
    visibility:hidden; /*允许浏览器渲染它，但是不显示出来*/
}
```
给浮动元素的容器添加一个clearfix的class，然后给这个class添加一个:after伪元素实现元素末尾添加一个看不见的块元素（Block element）清理浮动。

### 方式三：给父元素使用overflow:hidden;
这种方案让父容器形成了BFC（块级格式上下文），而BFC可以包含浮动，通常用来解决浮动父元素高度坍塌的问题。

可以给父元素添加以下属性来触发BFC：

- float 为 left | right

- overflow 为 hidden | auto | scorll

- display 为 table-cell | table-caption | inline-block

- position 为 absolute | fixed

这里可以给父元素设置overflow:auto，但是为了兼容IE最好使用overflow:hidden。

**缺点：**如果有内容出了盒子，用这种方法就会把多的部分裁切掉，所以这时候不能使用。

### 方式四：给浮动的元素的容器添加浮动

给浮动元素的容器也添加上浮动属性即可清除内部浮动，但是这样会使其整体浮动，影响布局，不推荐使用。
